<a href="https://colab.research.google.com/github/KatherinePalaciosaCortez/etl-data-pipeline-/blob/main/%20notebooks/aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/darkeyr0728/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

df = pd.read_csv(url)

df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

In [3]:
#Exploración de Datos

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

In [5]:
#Limpieza

aseguradoras = df.copy()

aseguradoras["nombre"] = aseguradoras["nombre"].str.title()
aseguradoras["pais"] = aseguradoras["pais"].str.title()

map_rating = {
    "alto": "Alto",
    "medio": "Medio",
    "bajo": "Bajo"
}

aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].str.lower().map(map_rating)
aseguradoras["rating_riesgo"] = aseguradoras["rating_riesgo"].fillna("No especificado")
aseguradoras["pais"] = aseguradoras["pais"].fillna("No especificado")

In [6]:

#Separar datos validos
validos = aseguradoras[
    aseguradoras['nombre'].notna() &
    aseguradoras['pais'].notna()&
    aseguradoras['rating_riesgo'].notna()
].copy()

rechazados = aseguradoras[
    aseguradoras['nombre'].isna() |
    aseguradoras['pais'].isna() |
    aseguradoras['rating_riesgo'].isna()
].copy()

In [7]:

#Motivo de Rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")

    if pd.isna(row['pais']):
        motivos.append("email_vacio")

    if pd.isna(row['rating_riesgo']):
        motivos.append("email_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [8]:
#Exportar Archivos
validos.to_csv("aseguradoras_curated.csv", index=False)

rechazados.to_csv("aseguradoras_rejects.csv", index=False)

In [9]:
#Conectar con Postgress
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_d64b_user:p6QnZIQqgOGUKctlfJR0R166FJ7kgt51@dpg-d6qu9dfgi27c73aabfog-a.oregon-postgres.render.com/etl_seguros_d64b"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 34.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [10]:

#Cargar Datos Postgress

validos.to_sql(
    'aseguradoras_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'aseguradoras_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [11]:

#Validar la carga
pd.read_sql(
"SELECT * FROM aseguradoras_curated LIMIT 10",
engine
)

   id_aseguradora          nombre             pais    rating_riesgo
0               1   Aseguradora 1       Costa Rica             Alto
1               2   Aseguradora 2      El Salvador             Bajo
2               3   Aseguradora 3      El Salvador  No especificado
3               4   Aseguradora 4       Costa Rica            Medio
4               5   Aseguradora 5       Elsalvador  No especificado
5               6   Aseguradora 6  No especificado            Medio
6               7   Aseguradora 7        Guatemala             Alto
7               8   Aseguradora 8           Panamá             Bajo
8               9   Aseguradora 9  No especificado             Bajo
9              10  Aseguradora 10           Panamá  No especificado