<a href="https://colab.research.google.com/github/KatherinePalaciosaCortez/etl-data-pipeline-/blob/main/%20notebooks/corredores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/darkeyr0728/etl-data-pipeline/refs/heads/main/data/raw/corredores.csv"

df = pd.read_csv(url)

df.head()

   id_corredor               nombre         zona    nivel  anios_experiencia
0            1    José López Flores  Paracentral      Mid                4.0
1            2    José Ortiz García     Centro     Junior                0.0
2            3   María Ramírez Cruz       Centro  SENIOR                 6.0
3            4  Fernanda Rojas Cruz          NaN  SENIOR                 8.0
4            5      Ana Gómez Rojas          NaN   Senior                4.0

In [3]:

#Exploración de Datos

df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_corredor        80 non-null     int64
 1   nombre             80 non-null     object
 2   zona               63 non-null     object
 3   nivel              68 non-null     object
 4   anios_experiencia  76 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 3.3+ KB

id_corredor           0
nombre                0
zona                 17
nivel                12
anios_experiencia     4
dtype: int64

In [5]:

#Limpieza de datos

corredores = df.copy()

corredores.columns = corredores.columns.str.strip().str.lower()

for col in corredores.select_dtypes(include='object').columns:
    corredores[col] = corredores[col].astype(str).str.strip()

corredores = corredores.replace(r'^\s*$', pd.NA, regex=True)



corredores = corredores.drop_duplicates()

In [7]:

#Separar datos validos
validos = corredores[
    corredores['nombre'].notna()
].copy()

rechazados = corredores[
    corredores['nombre'].isna()
].copy()

In [9]:

#Motivo de Rechazo
def motivo(row):

    motivos = []

    if pd.isna(row['nombre']):
        motivos.append("nombre_vacio")


    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [11]:
#Exportar Archivos
validos.to_csv("corredores_curated.csv", index=False)

rechazados.to_csv("corredores_rejects.csv", index=False)

In [12]:

#Conectar con Postgress
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_d64b_user:p6QnZIQqgOGUKctlfJR0R166FJ7kgt51@dpg-d6qu9dfgi27c73aabfog-a.oregon-postgres.render.com/etl_seguros_d64b"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 57.2 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [13]:
#Cargar Datos Postgress

validos.to_sql(
    'corredores_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'corredores_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [14]:
#Validar la carga
pd.read_sql(
"SELECT * FROM corredores_curated LIMIT 10",
engine
)

   id_corredor                 nombre         zona   nivel  anios_experiencia
0            1      José López Flores  Paracentral     Mid                4.0
1            2      José Ortiz García       Centro  Junior                0.0
2            3     María Ramírez Cruz       Centro  SENIOR                6.0
3            4    Fernanda Rojas Cruz          nan  SENIOR                8.0
4            5        Ana Gómez Rojas          nan  Senior                4.0
5            6  Sofía Reyes Hernández    Occidente   Elite                3.0
6            7   Pedro Vásquez Torres        Costa     nan                1.0
7            8  Paula Ortiz Hernández       Centro  Junior               17.0
8            9  Carlos Torres Vásquez  Paracentral  junior                2.0
9           10     Juan Cruz Castillo    Occidente     nan                7.0

In [15]:
#Validar la carga
pd.read_sql(
"SELECT * FROM corredores_curated ",
engine
)

,id_corredor,nombre,zona,nivel,anios_experiencia
0,1,José López Flores,Paracentral,Mid,4.0
1,2,José Ortiz García,Centro,Junior,0.0
2,3,María Ramírez Cruz,Centro,SENIOR,6.0
3,4,Fernanda Rojas Cruz,nan,SENIOR,8.0
4,5,Ana Gómez Rojas,nan,Senior,4.0
...,...,...,...,...,...
75,76,Sofía Morales Reyes,Costa,nan,2.0
76,77,Valeria Vásquez Mendoza,Centro,junior,NaN
77,78,Fernanda Reyes López,Occidente,Senior,5.0
78,79,Jorge Flores Martínez,Occidente,SENIOR,13.0
79,80,Pedro Reyes Rojas,Occidente,Elite,18.0